name: Build
on:
  push:
    tags:
      - 'dev'
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch Tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Run build
      run: |
        make status
        make push-image
