name: Build
on:
  push:
    tags:
      - 'dev'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run command
      run: make status

