name: Promote
on:
  push:
    tags:
      - 'test'
      - 'prod'

jobs:
  promote:
    name: Promote
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run command
        run: make status

