name: Pushed Tag
on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run command
      run: make status

