name: Pushed Tag
on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    env:
      BRANCH: $(git rev-parse --abbrev-ref HEAD)
      HASH: $(git rev-parse --short=7 HEAD)
    steps:
    - run: echo "Branch $BRANCH Hash $HASH"

